name: Test and Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_and_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11' # Puedes ajustar la versión de Java según tus necesidades

      - name: Run tests
        run: ./gradlew test

      - name: Build project
        run: ./gradlew build
