name: Test and Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_and_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run tests
        run: ../../DesarrolloDeApp/unq-desapp-2024s1-grupo-a/backend-desapp-api/gradlew test

      - name: Build project
        run: ../backend-desapp-api/gradlew build
